### ISSUE TITLE
[Bug]: compute sampler->delivery_rate numerical transformation error

### ISSUE THREAD

**Issue by adcen0107** [alibaba/xquic#184] opened 2022-06-01 06:47 UTC
### What happened?

xqc_sample.c  xqc_generate_sample()   
  if (sampler->interval != 0) {
        /* unit of interval is us */
        sampler->delivery_rate = (uint64_t)(1e6 * sampler->delivered / sampler->interval);   // error happened
    }

xqc_sample.h
    uint32_t         delivery_rate;

### Steps To Reproduce

Information and Steps to reproduce the behavior.

**Comment by RuiqiZhou** [comment] 2022-06-02 07:32
We'd appreciate it if you could tell us what and how the error happened.

**Comment by RuiqiZhou** [comment] 2022-06-17 08:02
Hello, because there are no reproducible steps, we will close this issue.
If necessary, reopen an issue and describe it in detail.

**Closed by RuiqiZhou** 2022-06-17 08:02 UTC
Labels: :raised_eyebrow: need more info

**Comment by adcen0107** [comment] 2022-06-25 02:21
相关信息已补充编辑，见上
