### ISSUE TITLE
test_client with 0-RTT

### ISSUE THREAD

**Issue by EasyCoderWei** [alibaba/xquic#98] opened 2022-02-22 02:29 UTC
### Discussed in https://github.com/alibaba/xquic/discussions/97

<div type='discussions-op-text'>

<sup>Originally posted by **EasyCoderWei** February 21, 2022</sup>
I want to test HTTP3 with 0-RTT function, but I cann't find any options in `test_client --help` .
Does test_client tool support this ?</div>

**Comment by RuiqiZhou** [comment] 2022-02-22 02:54
Hi, this is not a bug or feature request. we can answer you in the discussion forum and I will close this issue.

**Closed by RuiqiZhou** 2022-02-22 02:54 UTC
Labels: discussion
